name: LoginMe
version: '1.0'
main: bxn4.oneplugins.loginme.LoginMe
api-version: 1.19
description: A simple login plugin
author: BXn4
website: https://github.com/OnePlugins/LoginMe
commands:
  login:
    description: Login command.
    usage: /login <password>
  register:
    description: Register command.
    usage: /register <password> <password>
    aliases:
      - reg
  logout:
    description: Logout from the server.
    usage: /logout
  password:
    description: Generate a random password.
    usage: /password <length>
  registerplayer:
    description: Registering a player by an admin.
    usage: /registerplayer <player> <password>
      - regplayer
    permission: loginme.registerplayer
  setpass:
    description: Change password of a player.
    usage: /setpass <player> <password>
    permission: loginme.setpass
  loginbackup:
    description: Simple backup code, to reset your password.
    usage:
    - /loginbackup create
    - /loginbackup code <code>
    - /loginbackup setpass <newpassword>
  loginbackup create:
    description: Creating a 8 digits backup code.
    usage: /loginbackup create
  loginbackup code:
    description: For use your backup code.
    usage: /loginbackup code <code>
  loginbackup setpass:
      description: Changing the password.
      usage: /loginbackup setpass <newpassword>
  changepass:
    description: Changing your password.
    usage: /changepass <oldpassword> <newpassword>
