name: LoginMe
version: '${project.version}'
main: bxn4.oneplugins.loginme.LoginMe
api-version: 1.19
description: A simple login plugin
author: BXn4
commands:
  login:
    description: Login command
    usage: /login <password>
  register:
    description: Register command
    usage: /register <password> <password>
    aliases:
      - reg
  logout:
    description: Logout from the server
    usage: /logout